//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_client_AgImob.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareDateProprietar", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse AdaugareDateProprietar(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareDateProprietar", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse> AdaugareDateProprietarAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest request);
        
        // CODEGEN: Generating message contract since element name tipulimob from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareTipImobil", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse AdaugareTipImobil(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareTipImobil", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse> AdaugareTipImobilAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareImobil", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse AdaugareImobil(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareImobil", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse> AdaugareImobilAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereDateProprietar", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse StergereDateProprietar(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereDateProprietar", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse> StergereDateProprietarAsync(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereTipImobil", ReplyAction="*")]
        void StergereTipImobil(int Id_imobil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereTipImobil", ReplyAction="*")]
        System.Threading.Tasks.Task StergereTipImobilAsync(int Id_imobil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereImobil", ReplyAction="*")]
        void StergereImobil(int Id_prop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereImobil", ReplyAction="*")]
        System.Threading.Tasks.Task StergereImobilAsync(int Id_prop);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareImobil", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse ModificareImobil(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareImobil", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse> ModificareImobilAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest request);
        
        // CODEGEN: Generating message contract since element name tipulimob from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareTipImobil", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse ModificareTipImobil(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareTipImobil", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse> ModificareTipImobilAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareDatePropr", ReplyAction="*")]
        Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse ModificareDatePropr(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareDatePropr", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse> ModificareDateProprAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareDateProprietarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareDateProprietar", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequestBody Body;
        
        public AdaugareDateProprietarRequest() {
        }
        
        public AdaugareDateProprietarRequest(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareDateProprietarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public AdaugareDateProprietarRequestBody() {
        }
        
        public AdaugareDateProprietarRequestBody(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            this.cnp = cnp;
            this.nume = nume;
            this.prenume = prenume;
            this.adresa = adresa;
            this.telefon = telefon;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareDateProprietarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareDateProprietarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponseBody Body;
        
        public AdaugareDateProprietarResponse() {
        }
        
        public AdaugareDateProprietarResponse(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareDateProprietarResponseBody {
        
        public AdaugareDateProprietarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareTipImobilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareTipImobil", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequestBody Body;
        
        public AdaugareTipImobilRequest() {
        }
        
        public AdaugareTipImobilRequest(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareTipImobilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_imobil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipulimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descrieretip;
        
        public AdaugareTipImobilRequestBody() {
        }
        
        public AdaugareTipImobilRequestBody(int Id_imobil, string tipulimob, string descrieretip) {
            this.Id_imobil = Id_imobil;
            this.tipulimob = tipulimob;
            this.descrieretip = descrieretip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareTipImobilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareTipImobilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponseBody Body;
        
        public AdaugareTipImobilResponse() {
        }
        
        public AdaugareTipImobilResponse(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareTipImobilResponseBody {
        
        public AdaugareTipImobilResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareImobilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareImobil", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequestBody Body;
        
        public AdaugareImobilRequest() {
        }
        
        public AdaugareImobilRequest(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareImobilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_prop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adresaimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string camere;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string marimeimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pretimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dataimob;
        
        public AdaugareImobilRequestBody() {
        }
        
        public AdaugareImobilRequestBody(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            this.Id_prop = Id_prop;
            this.cnp = cnp;
            this.tipimob = tipimob;
            this.adresaimob = adresaimob;
            this.camere = camere;
            this.marimeimob = marimeimob;
            this.pretimob = pretimob;
            this.dataimob = dataimob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareImobilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareImobilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponseBody Body;
        
        public AdaugareImobilResponse() {
        }
        
        public AdaugareImobilResponse(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareImobilResponseBody {
        
        public AdaugareImobilResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergereDateProprietarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergereDateProprietar", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequestBody Body;
        
        public StergereDateProprietarRequest() {
        }
        
        public StergereDateProprietarRequest(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StergereDateProprietarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        public StergereDateProprietarRequestBody() {
        }
        
        public StergereDateProprietarRequestBody(string cnp) {
            this.cnp = cnp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergereDateProprietarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergereDateProprietarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponseBody Body;
        
        public StergereDateProprietarResponse() {
        }
        
        public StergereDateProprietarResponse(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StergereDateProprietarResponseBody {
        
        public StergereDateProprietarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareImobilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareImobil", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequestBody Body;
        
        public ModificareImobilRequest() {
        }
        
        public ModificareImobilRequest(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificareImobilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_prop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adresaimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string camere;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string marimeimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pretimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dataimob;
        
        public ModificareImobilRequestBody() {
        }
        
        public ModificareImobilRequestBody(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            this.Id_prop = Id_prop;
            this.cnp = cnp;
            this.tipimob = tipimob;
            this.adresaimob = adresaimob;
            this.camere = camere;
            this.marimeimob = marimeimob;
            this.pretimob = pretimob;
            this.dataimob = dataimob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareImobilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareImobilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponseBody Body;
        
        public ModificareImobilResponse() {
        }
        
        public ModificareImobilResponse(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificareImobilResponseBody {
        
        public ModificareImobilResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareTipImobilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareTipImobil", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequestBody Body;
        
        public ModificareTipImobilRequest() {
        }
        
        public ModificareTipImobilRequest(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificareTipImobilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_imobil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipulimob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descrieretip;
        
        public ModificareTipImobilRequestBody() {
        }
        
        public ModificareTipImobilRequestBody(int Id_imobil, string tipulimob, string descrieretip) {
            this.Id_imobil = Id_imobil;
            this.tipulimob = tipulimob;
            this.descrieretip = descrieretip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareTipImobilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareTipImobilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponseBody Body;
        
        public ModificareTipImobilResponse() {
        }
        
        public ModificareTipImobilResponse(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificareTipImobilResponseBody {
        
        public ModificareTipImobilResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareDateProprRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareDatePropr", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequestBody Body;
        
        public ModificareDateProprRequest() {
        }
        
        public ModificareDateProprRequest(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificareDateProprRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public ModificareDateProprRequestBody() {
        }
        
        public ModificareDateProprRequestBody(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            this.cnp = cnp;
            this.nume = nume;
            this.prenume = prenume;
            this.adresa = adresa;
            this.telefon = telefon;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareDateProprResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareDateProprResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponseBody Body;
        
        public ModificareDateProprResponse() {
        }
        
        public ModificareDateProprResponse(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificareDateProprResponseBody {
        
        public ModificareDateProprResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Aplicatie_client_AgImob.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Aplicatie_client_AgImob.ServiceReference1.WebService1Soap>, Aplicatie_client_AgImob.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareDateProprietar(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest request) {
            return base.Channel.AdaugareDateProprietar(request);
        }
        
        public void AdaugareDateProprietar(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.email = email;
            Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareDateProprietar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareDateProprietarAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest request) {
            return base.Channel.AdaugareDateProprietarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarResponse> AdaugareDateProprietarAsync(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareDateProprietarRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.email = email;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareDateProprietarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareTipImobil(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest request) {
            return base.Channel.AdaugareTipImobil(request);
        }
        
        public void AdaugareTipImobil(int Id_imobil, string tipulimob, string descrieretip) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequestBody();
            inValue.Body.Id_imobil = Id_imobil;
            inValue.Body.tipulimob = tipulimob;
            inValue.Body.descrieretip = descrieretip;
            Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareTipImobil(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareTipImobilAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest request) {
            return base.Channel.AdaugareTipImobilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilResponse> AdaugareTipImobilAsync(int Id_imobil, string tipulimob, string descrieretip) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareTipImobilRequestBody();
            inValue.Body.Id_imobil = Id_imobil;
            inValue.Body.tipulimob = tipulimob;
            inValue.Body.descrieretip = descrieretip;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareTipImobilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareImobil(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest request) {
            return base.Channel.AdaugareImobil(request);
        }
        
        public void AdaugareImobil(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequestBody();
            inValue.Body.Id_prop = Id_prop;
            inValue.Body.cnp = cnp;
            inValue.Body.tipimob = tipimob;
            inValue.Body.adresaimob = adresaimob;
            inValue.Body.camere = camere;
            inValue.Body.marimeimob = marimeimob;
            inValue.Body.pretimob = pretimob;
            inValue.Body.dataimob = dataimob;
            Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareImobil(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.AdaugareImobilAsync(Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest request) {
            return base.Channel.AdaugareImobilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilResponse> AdaugareImobilAsync(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.AdaugareImobilRequestBody();
            inValue.Body.Id_prop = Id_prop;
            inValue.Body.cnp = cnp;
            inValue.Body.tipimob = tipimob;
            inValue.Body.adresaimob = adresaimob;
            inValue.Body.camere = camere;
            inValue.Body.marimeimob = marimeimob;
            inValue.Body.pretimob = pretimob;
            inValue.Body.dataimob = dataimob;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).AdaugareImobilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.StergereDateProprietar(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest request) {
            return base.Channel.StergereDateProprietar(request);
        }
        
        public void StergereDateProprietar(string cnp) {
            Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequestBody();
            inValue.Body.cnp = cnp;
            Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).StergereDateProprietar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.StergereDateProprietarAsync(Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest request) {
            return base.Channel.StergereDateProprietarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarResponse> StergereDateProprietarAsync(string cnp) {
            Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.StergereDateProprietarRequestBody();
            inValue.Body.cnp = cnp;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).StergereDateProprietarAsync(inValue);
        }
        
        public void StergereTipImobil(int Id_imobil) {
            base.Channel.StergereTipImobil(Id_imobil);
        }
        
        public System.Threading.Tasks.Task StergereTipImobilAsync(int Id_imobil) {
            return base.Channel.StergereTipImobilAsync(Id_imobil);
        }
        
        public void StergereImobil(int Id_prop) {
            base.Channel.StergereImobil(Id_prop);
        }
        
        public System.Threading.Tasks.Task StergereImobilAsync(int Id_prop) {
            return base.Channel.StergereImobilAsync(Id_prop);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareImobil(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest request) {
            return base.Channel.ModificareImobil(request);
        }
        
        public void ModificareImobil(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequestBody();
            inValue.Body.Id_prop = Id_prop;
            inValue.Body.cnp = cnp;
            inValue.Body.tipimob = tipimob;
            inValue.Body.adresaimob = adresaimob;
            inValue.Body.camere = camere;
            inValue.Body.marimeimob = marimeimob;
            inValue.Body.pretimob = pretimob;
            inValue.Body.dataimob = dataimob;
            Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareImobil(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareImobilAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest request) {
            return base.Channel.ModificareImobilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareImobilResponse> ModificareImobilAsync(int Id_prop, string cnp, string tipimob, string adresaimob, string camere, string marimeimob, string pretimob, string dataimob) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareImobilRequestBody();
            inValue.Body.Id_prop = Id_prop;
            inValue.Body.cnp = cnp;
            inValue.Body.tipimob = tipimob;
            inValue.Body.adresaimob = adresaimob;
            inValue.Body.camere = camere;
            inValue.Body.marimeimob = marimeimob;
            inValue.Body.pretimob = pretimob;
            inValue.Body.dataimob = dataimob;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareImobilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareTipImobil(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest request) {
            return base.Channel.ModificareTipImobil(request);
        }
        
        public void ModificareTipImobil(int Id_imobil, string tipulimob, string descrieretip) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequestBody();
            inValue.Body.Id_imobil = Id_imobil;
            inValue.Body.tipulimob = tipulimob;
            inValue.Body.descrieretip = descrieretip;
            Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareTipImobil(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareTipImobilAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest request) {
            return base.Channel.ModificareTipImobilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilResponse> ModificareTipImobilAsync(int Id_imobil, string tipulimob, string descrieretip) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareTipImobilRequestBody();
            inValue.Body.Id_imobil = Id_imobil;
            inValue.Body.tipulimob = tipulimob;
            inValue.Body.descrieretip = descrieretip;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareTipImobilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareDatePropr(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest request) {
            return base.Channel.ModificareDatePropr(request);
        }
        
        public void ModificareDatePropr(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.email = email;
            Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse retVal = ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareDatePropr(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse> Aplicatie_client_AgImob.ServiceReference1.WebService1Soap.ModificareDateProprAsync(Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest request) {
            return base.Channel.ModificareDateProprAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprResponse> ModificareDateProprAsync(string cnp, string nume, string prenume, string adresa, string telefon, string email) {
            Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest inValue = new Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequest();
            inValue.Body = new Aplicatie_client_AgImob.ServiceReference1.ModificareDateProprRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.email = email;
            return ((Aplicatie_client_AgImob.ServiceReference1.WebService1Soap)(this)).ModificareDateProprAsync(inValue);
        }
    }
}
